import { MetaMaskTokenDef, MetaMaskChainDef, MetaMaskTradingKnowledge } from '../types';

export const METAMASK_CHAINS: Record<string, MetaMaskChainDef> = {
  polygon: {
    chain_key: 'polygon',
    name: 'Polygon PoS',
    chain_id: 137,
    native_symbol: 'POL',
    native_name: 'Polygon Ecosystem Token',
    native_usd_price: 0.1143,
    native_balance: 53.74932,
    native_usd_value: 6.14,
    gas_price_gwei: 32.5,
    gas_status: 'OPTIMAL',
    transfer_cost_usd: 0.0012,
    explorer_url: 'https://polygonscan.com',
    rpc_url: 'https://polygon-rpc.com',
    is_active: true,
    tokens_count: 5
  },
  ethereum: {
    chain_key: 'ethereum',
    name: 'Ethereum Mainnet',
    chain_id: 1,
    native_symbol: 'ETH',
    native_name: 'Ether',
    native_usd_price: 2472.65,
    native_balance: 0.00019,
    native_usd_value: 0.47,
    gas_price_gwei: 14.2,
    gas_status: 'EXPENSIVE',
    transfer_cost_usd: 1.85,
    explorer_url: 'https://etherscan.io',
    rpc_url: 'https://eth.llamarpc.com',
    is_active: true,
    tokens_count: 3
  },
  arbitrum: {
    chain_key: 'arbitrum',
    name: 'Arbitrum One',
    chain_id: 42161,
    native_symbol: 'ETH',
    native_name: 'Ether (L2)',
    native_usd_price: 2472.65,
    native_balance: 0.0,
    native_usd_value: 0.0,
    gas_price_gwei: 0.1,
    gas_status: 'OPTIMAL',
    transfer_cost_usd: 0.04,
    explorer_url: 'https://arbiscan.io',
    rpc_url: 'https://arb1.arbitrum.io/rpc',
    is_active: true,
    tokens_count: 2
  },
  base: {
    chain_key: 'base',
    name: 'Base',
    chain_id: 8453,
    native_symbol: 'ETH',
    native_name: 'Ether (Base)',
    native_usd_price: 2472.65,
    native_balance: 0.0,
    native_usd_value: 0.0,
    gas_price_gwei: 0.05,
    gas_status: 'OPTIMAL',
    transfer_cost_usd: 0.02,
    explorer_url: 'https://basescan.org',
    rpc_url: 'https://mainnet.base.org',
    is_active: true,
    tokens_count: 2
  },
  bsc: {
    chain_key: 'bsc',
    name: 'BNB Smart Chain',
    chain_id: 56,
    native_symbol: 'BNB',
    native_name: 'BNB',
    native_usd_price: 585.40,
    native_balance: 0.0,
    native_usd_value: 0.0,
    gas_price_gwei: 3.0,
    gas_status: 'OPTIMAL',
    transfer_cost_usd: 0.08,
    explorer_url: 'https://bscscan.com',
    rpc_url: 'https://bsc-dataseed.binance.org',
    is_active: true,
    tokens_count: 2
  }
};

export const INITIAL_METAMASK_TOKENS: MetaMaskTokenDef[] = [
  // --- POLYGON POS TOKENS (Screenshot Match) ---
  {
    symbol: 'POL',
    name: 'Polygon Ecosystem Token',
    chain_key: 'polygon',
    chain_name: 'Polygon PoS',
    chain_id: 137,
    contract_address: '0x0000000000000000000000000000000000001010',
    decimals: 18,
    category: 'GAS_NATIVE',
    usd_price: 0.1143,
    change_24h_percent: 5.36,
    balance: 53.74932,
    usd_value: 6.14,
    is_gas_token: true,
    coingecko_id: 'polygon-ecosystem-token',
    verified_metamask: true
  },
  {
    symbol: 'USDC.E',
    name: 'USD Coin (PoS)',
    chain_key: 'polygon',
    chain_name: 'Polygon PoS',
    chain_id: 137,
    contract_address: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174',
    decimals: 6,
    category: 'STABLECOIN',
    usd_price: 0.9999,
    change_24h_percent: -0.01,
    balance: 0.94855,
    usd_value: 0.95,
    is_gas_token: false,
    coingecko_id: 'usd-coin',
    verified_metamask: true
  },
  {
    symbol: 'USDC',
    name: 'USD Coin (Native)',
    chain_key: 'polygon',
    chain_name: 'Polygon PoS',
    chain_id: 137,
    contract_address: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
    decimals: 6,
    category: 'STABLECOIN',
    usd_price: 0.9999,
    change_24h_percent: 0.00,
    balance: 0.30000,
    usd_value: 0.30,
    is_gas_token: false,
    coingecko_id: 'usd-coin',
    verified_metamask: true
  },
  {
    symbol: 'WETH',
    name: 'Wrapped Ether (Polygon)',
    chain_key: 'polygon',
    chain_name: 'Polygon PoS',
    chain_id: 137,
    contract_address: '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619',
    decimals: 18,
    category: 'WRAPPED_NATIVE',
    usd_price: 2472.65,
    change_24h_percent: 0.93,
    balance: 0.0,
    usd_value: 0.0,
    is_gas_token: false,
    coingecko_id: 'weth',
    verified_metamask: true
  },
  {
    symbol: 'USDT',
    name: 'Tether USD (Polygon)',
    chain_key: 'polygon',
    chain_name: 'Polygon PoS',
    chain_id: 137,
    contract_address: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
    decimals: 6,
    category: 'STABLECOIN',
    usd_price: 1.0001,
    change_24h_percent: 0.02,
    balance: 0.0,
    usd_value: 0.0,
    is_gas_token: false,
    coingecko_id: 'tether',
    verified_metamask: true
  },

  // --- ETHEREUM MAINNET TOKENS (Screenshot Match) ---
  {
    symbol: 'ETH',
    name: 'Ethereum',
    chain_key: 'ethereum',
    chain_name: 'Ethereum Mainnet',
    chain_id: 1,
    contract_address: '0x0000000000000000000000000000000000000000',
    decimals: 18,
    category: 'GAS_NATIVE',
    usd_price: 2472.65,
    change_24h_percent: 0.93,
    balance: 0.00019,
    usd_value: 0.47,
    is_gas_token: true,
    coingecko_id: 'ethereum',
    verified_metamask: true
  },
  {
    symbol: 'USDC',
    name: 'USD Coin (Ethereum)',
    chain_key: 'ethereum',
    chain_name: 'Ethereum Mainnet',
    chain_id: 1,
    contract_address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    decimals: 6,
    category: 'STABLECOIN',
    usd_price: 0.9996,
    change_24h_percent: -0.03,
    balance: 0.37825,
    usd_value: 0.38,
    is_gas_token: false,
    coingecko_id: 'usd-coin',
    verified_metamask: true
  },
  {
    symbol: 'USDT',
    name: 'Tether USD (Ethereum)',
    chain_key: 'ethereum',
    chain_name: 'Ethereum Mainnet',
    chain_id: 1,
    contract_address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    decimals: 6,
    category: 'STABLECOIN',
    usd_price: 1.0000,
    change_24h_percent: 0.01,
    balance: 0.0,
    usd_value: 0.0,
    is_gas_token: false,
    coingecko_id: 'tether',
    verified_metamask: true
  },

  // --- ARBITRUM ONE ---
  {
    symbol: 'USDC',
    name: 'USD Coin (Arbitrum Native)',
    chain_key: 'arbitrum',
    chain_name: 'Arbitrum One',
    chain_id: 42161,
    contract_address: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
    decimals: 6,
    category: 'STABLECOIN',
    usd_price: 1.0000,
    change_24h_percent: 0.00,
    balance: 0.0,
    usd_value: 0.0,
    is_gas_token: false,
    coingecko_id: 'usd-coin',
    verified_metamask: true
  },
  {
    symbol: 'ARB',
    name: 'Arbitrum',
    chain_key: 'arbitrum',
    chain_name: 'Arbitrum One',
    chain_id: 42161,
    contract_address: '0x912CE59144191C1204E64559FE8253a0e49E6548',
    decimals: 18,
    category: 'LAYER2',
    usd_price: 0.524,
    change_24h_percent: 3.12,
    balance: 0.0,
    usd_value: 0.0,
    is_gas_token: false,
    coingecko_id: 'arbitrum',
    verified_metamask: true
  },

  // --- BASE ---
  {
    symbol: 'USDC',
    name: 'USD Coin (Base Native)',
    chain_key: 'base',
    chain_name: 'Base',
    chain_id: 8453,
    contract_address: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    decimals: 6,
    category: 'STABLECOIN',
    usd_price: 1.0000,
    change_24h_percent: 0.00,
    balance: 0.0,
    usd_value: 0.0,
    is_gas_token: false,
    coingecko_id: 'usd-coin',
    verified_metamask: true
  }
];

export const INITIAL_TRADING_KNOWLEDGE: MetaMaskTradingKnowledge[] = [
  {
    category: 'DEX_ROUTING',
    title: 'Polygon PoS DEX Router & Aggregatoren',
    chain: 'Polygon (137)',
    symbol: 'POL / USDC / USDT / WETH',
    summary: 'Optimales Routing auf Polygon über QuickSwap V3, Uniswap V3 und 1inch Aggregator.',
    details: 'QuickSwap Router (0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff) und Uniswap V3 SwapRouter (0xE592427A0AEce92De3Edee1F18E0157C05861564). Geringste Slippage für USDC.e -> USDC Native Swaps über Uniswap V3 Pool (0.01% Fee Tier).',
    apis_used: ['https://api.1inch.dev/swap/v6.0/137/quote', 'https://api.coingecko.com', 'https://yields.llama.fi'],
    last_updated: new Date().toISOString(),
    confidence: 0.98
  },
  {
    category: 'GAS_STRATEGY',
    title: 'Polygon EIP-1559 Gas-Ökonomie',
    chain: 'Polygon (137)',
    symbol: 'POL',
    summary: 'Mindestens 30-35 Gwei Priority Fee für verlässliche Inklusion unter 5 Sekunden.',
    details: 'Polygon PoS Bor-Nodes droppen Transaktionen mit < 30 Gwei maxPriorityFeePerGas. Für Standard-Transfers reichen 35 Gwei Priority Fee bei 60-80 Gwei Max Fee. Transferkosten betragen ca. 0.001 - 0.002 POL ($0.0002).',
    apis_used: ['https://gasstation.polygon.technology/v2', 'https://polygon-rpc.com'],
    last_updated: new Date().toISOString(),
    confidence: 0.99
  },
  {
    category: 'ARBITRAGE_YIELD',
    title: 'Multi-Chain Stablecoin Parität & Bridge-Spreads',
    chain: 'Multi-Chain',
    symbol: 'USDC vs. USDC.E',
    summary: 'USDC.e und Native USDC handeln auf Polygon bei ca. 1.000:1 mit marginalen 0.02% Swapping Fees.',
    details: 'Bridge-Transfers von Ethereum L1 zu Polygon oder Arbitrum kosten auf L1 15-30 USD Gas. Für Kleinbeträge (<$100) sind direkte L2-Trades oder CEX-Deposits vorzuziehen.',
    apis_used: ['https://api.coingecko.com/api/v3/simple/price', 'https://yields.llama.fi/pools'],
    last_updated: new Date().toISOString(),
    confidence: 0.95
  },
  {
    category: 'WEB_RESEARCH',
    title: 'MetaMask Standard-Token Erkennung & ERC-20 Balances',
    chain: 'Ethereum & EVM Chains',
    symbol: 'ERC-20',
    summary: 'Batch-Balance-Abfrage via Multicall3 (0xca11bde05977b3631167028862be2a173976ca11) oder RPC balanceOf.',
    details: 'MetaMask erkennt Token anhand der Standard ERC-20 ABI: balanceOf, decimals, symbol, name. Der Agent fragt on-chain alle registrierten Contracts direkt über Polygon und Ethereum RPCs ab.',
    apis_used: ['https://polygon-rpc.com', 'https://eth.llamarpc.com'],
    last_updated: new Date().toISOString(),
    confidence: 0.97
  }
];
